-- All analog commands (with value -1.0 to 1.0)
local analog_commands = {
    {cmd = 2001, name = "Joystick pitch", value = 0.3},
    {cmd = 2002, name = "Joystick roll", value = -0.4},
    {cmd = 2003, name = "Joystick rudder", value = 0.5},
    {cmd = 2004, name = "Joystick thrust (both)", value = -0.6},
    {cmd = 2005, name = "Joystick left thrust", value = -0.5},
    {cmd = 2006, name = "Joystick right thrust", value = -0.5},
    {cmd = 2007, name = "Mouse camera L/R", value = 0.3},
    {cmd = 2008, name = "Mouse camera U/D", value = -0.3},
    {cmd = 2009, name = "Mouse camera zoom", value = 0.5},
    {cmd = 2010, name = "Joystick camera L/R", value = 0.4},
    {cmd = 2011, name = "Joystick camera U/D", value = -0.4},
    {cmd = 2012, name = "Joystick camera zoom", value = 0.6},
    {cmd = 2013, name = "Mouse pitch", value = 0.2},
    {cmd = 2014, name = "Mouse roll", value = -0.2},
    {cmd = 2015, name = "Mouse rudder", value = 0.3},
    {cmd = 2016, name = "Mouse thrust (both)", value = -0.7},
    {cmd = 2017, name = "Mouse left thrust", value = -0.5},
    {cmd = 2018, name = "Mouse right thrust", value = -0.5},
    {cmd = 2019, name = "Mouse trim pitch", value = 0.1},
    {cmd = 2020, name = "Mouse trim roll", value = -0.1},
    {cmd = 2021, name = "Mouse trim rudder", value = 0.1},
    {cmd = 2022, name = "Joystick trim pitch", value = 0.15},
    {cmd = 2023, name = "Joystick trim roll", value = -0.15},
    {cmd = 2024, name = "Trim rudder", value = 0.2},
    {cmd = 2025, name = "Mouse radar antenna L/R", value = 0.5},
    {cmd = 2026, name = "Mouse radar antenna U/D", value = -0.5},
    {cmd = 2027, name = "Joystick radar antenna L/R", value = 0.6},
    {cmd = 2028, name = "Joystick radar antenna U/D", value = -0.6},
    {cmd = 2029, name = "Mouse MFD zoom", value = 0.4},
    {cmd = 2030, name = "Joystick MFD zoom", value = 0.4},
    {cmd = 2031, name = "Mouse selecter L/R", value = 0.5},
    {cmd = 2032, name = "Mouse selecter U/D", value = -0.5},
    {cmd = 2033, name = "Joystick selecter L/R", value = 0.5},
    {cmd = 2034, name = "Joystick selecter U/D", value = -0.5},
}

-- All discrete commands (value is absent, just call with command number)
local discrete_commands = {
    {cmd = 7, name = "Cockpit view"},
    {cmd = 8, name = "External view"},
    {cmd = 9, name = "Fly-by view"},
    {cmd = 10, name = "Ground units view"},
    {cmd = 11, name = "Civilian transport view"},
    {cmd = 12, name = "Chase view"},
    {cmd = 13, name = "Navy view"},
    {cmd = 14, name = "Close air combat view"},
    {cmd = 15, name = "Theater view"},
    {cmd = 16, name = "Airfield (free camera) view"},
    {cmd = 17, name = "Instruments panel view on"},
    {cmd = 18, name = "Instruments panel view off"},
    {cmd = 19, name = "Padlock toggle"},
    {cmd = 20, name = "Stop padlock"},
    {cmd = 21, name = "External view for my plane"},
    {cmd = 22, name = "Auto chase for weapon"},
    {cmd = 23, name = "View allies only"},
    {cmd = 24, name = "View enemies only"},
    {cmd = 26, name = "View allies & enemies"},
    {cmd = 28, name = "Rotate camera left fast"},
    {cmd = 29, name = "Rotate camera right fast"},
    {cmd = 30, name = "Rotate camera up fast"},
    {cmd = 31, name = "Rotate camera down fast"},
    {cmd = 32, name = "Rotate camera left slow"},
    {cmd = 33, name = "Rotate camera right slow"},
    {cmd = 34, name = "Rotate camera up slow"},
    {cmd = 35, name = "Rotate camera down slow"},
    {cmd = 36, name = "Return camera to default"},
    {cmd = 37, name = "View zoom in fast"},
    {cmd = 38, name = "View zoom out fast"},
    {cmd = 39, name = "View zoom in slow"},
    {cmd = 40, name = "View zoom out slow"},
    {cmd = 41, name = "Pan camera left"},
    {cmd = 42, name = "Pan camera right"},
    {cmd = 43, name = "Pan camera up"},
    {cmd = 44, name = "Pan camera down"},
    {cmd = 45, name = "Pan camera left slow"},
    {cmd = 46, name = "Pan camera right slow"},
    {cmd = 47, name = "Pan camera up slow"},
    {cmd = 48, name = "Pan camera down slow"},
    {cmd = 49, name = "Disable panning camera"},
    {cmd = 50, name = "Allies chat"},
    {cmd = 51, name = "Mission quit"},
    {cmd = 52, name = "Suspend/resume model time"},
    {cmd = 53, name = "Accelerate model time"},
    {cmd = 54, name = "Step by step simulation"},
    {cmd = 55, name = "Take control in track"},
    {cmd = 57, name = "Common chat"},
    {cmd = 59, name = "Altitude stabilization"},
    {cmd = 62, name = "Autopilot"},
    {cmd = 63, name = "Auto-thrust"},
    {cmd = 64, name = "Power up"},
    {cmd = 65, name = "Power down"},
    {cmd = 68, name = "Gear"},
    {cmd = 69, name = "Hook"},
    {cmd = 70, name = "Pack wings"},
    {cmd = 71, name = "Canopy"},
    {cmd = 72, name = "Flaps"},
    {cmd = 73, name = "Air brake"},
    {cmd = 74, name = "Wheel brakes on"},
    {cmd = 75, name = "Wheel brakes off"},
    {cmd = 76, name = "Release drogue chute"},
    {cmd = 77, name = "Drop snar"},
    {cmd = 78, name = "Wingtip smoke"},
    {cmd = 79, name = "Refuel on"},
    {cmd = 80, name = "Refuel off"},
    {cmd = 81, name = "Salvo"},
    {cmd = 82, name = "Jettison weapons"},
    {cmd = 83, name = "Eject"},
    {cmd = 84, name = "Fire on"},
    {cmd = 85, name = "Fire off"},
    {cmd = 86, name = "Radar"},
    {cmd = 87, name = "EOS"},
    {cmd = 88, name = "Rotate radar antenna left"},
    {cmd = 89, name = "Rotate radar antenna right"},
    {cmd = 90, name = "Rotate radar antenna up"},
    {cmd = 91, name = "Rotate radar antenna down"},
    {cmd = 92, name = "Center radar antenna"},
    {cmd = 93, name = "Trim left"},
    {cmd = 94, name = "Trim right"},
    {cmd = 95, name = "Trim up"},
    {cmd = 96, name = "Trim down"},
    {cmd = 97, name = "Cancel trimming"},
    {cmd = 98, name = "Trim rudder left"},
    {cmd = 99, name = "Trim rudder right"},
    {cmd = 100, name = "Lock target"},
    {cmd = 101, name = "Change weapon"},
    {cmd = 102, name = "Change target"},
    {cmd = 103, name = "MFD zoom in"},
    {cmd = 104, name = "MFD zoom out"},
    {cmd = 106, name = "BVR mode"},
    {cmd = 107, name = "VS mode"},
    {cmd = 108, name = "Bore mode"},
    {cmd = 109, name = "Helmet mode"},
    {cmd = 110, name = "FI0 mode"},
    {cmd = 111, name = "A2G mode"},
    {cmd = 112, name = "Grid mode"},
    {cmd = 113, name = "Cannon"},
    {cmd = 114, name = "Wingman - RTB"},
    {cmd = 115, name = "Wingman - rejoin"},
    {cmd = 116, name = "Wingman - toggle formation"},
    {cmd = 117, name = "Wingman - join up"},
    {cmd = 118, name = "Wingman - attack my target"},
    {cmd = 119, name = "Wingman - cover my six"},
    {cmd = 120, name = "Take off from ship"},
    {cmd = 121, name = "Cobra"},
    {cmd = 122, name = "Sound on/off"},
    {cmd = 123, name = "Sound recording on"},
    {cmd = 124, name = "Sound recording off"},
    {cmd = 125, name = "View right mirror on"},
    {cmd = 126, name = "View right mirror off"},
    {cmd = 127, name = "View left mirror on"},
    {cmd = 128, name = "View left mirror off"},
    {cmd = 129, name = "Natural head movement view"},
    {cmd = 131, name = "LSO view"},
    {cmd = 135, name = "Weapon to target view"},
    {cmd = 136, name = "Active jamming"},
    {cmd = 137, name = "Increase details level"},
    {cmd = 138, name = "Decrease details level"},
    {cmd = 139, name = "Scan zone left"},
    {cmd = 140, name = "Scan zone right"},
    {cmd = 141, name = "Scan zone up"},
    {cmd = 142, name = "Scan zone down"},
    {cmd = 143, name = "Unlock target"},
    {cmd = 144, name = "Reset master warning"},
    {cmd = 145, name = "Flaps on"},
    {cmd = 146, name = "Flaps off"},
    {cmd = 147, name = "Air brake on"},
    {cmd = 148, name = "Air brake off"},
    {cmd = 149, name = "Weapons view"},
    {cmd = 150, name = "Static objects view"},
    {cmd = 151, name = "Mission targets view"},
    {cmd = 152, name = "Info bar details"},
    {cmd = 155, name = "Refueling boom"},
    {cmd = 156, name = "HUD color selection"},
    {cmd = 158, name = "Jump to terrain view"},
    {cmd = 159, name = "F11 camera forward"},
    {cmd = 160, name = "F11 camera backward"},
    {cmd = 161, name = "Power up left engine"},
    {cmd = 162, name = "Power down left engine"},
    {cmd = 163, name = "Power up right engine"},
    {cmd = 164, name = "Power down right engine"},
    {cmd = 169, name = "Immortal mode"},
    {cmd = 175, name = "On-board lights"},
    {cmd = 176, name = "Drop snar once"},
    {cmd = 177, name = "Default cockpit angle"},
    {cmd = 178, name = "Jettison fuel tanks"},
    {cmd = 179, name = "Wingmen commands panel"},
    {cmd = 180, name = "Reverse objects switching"},
    {cmd = 181, name = "Forward objects switching"},
    {cmd = 182, name = "Ignore current object"},
    {cmd = 183, name = "View all ignored objects"},
    {cmd = 184, name = "Padlock terrain point"},
    {cmd = 185, name = "Reverse camera"},
    {cmd = 186, name = "Plane up"},
    {cmd = 187, name = "Plane down"},
    {cmd = 188, name = "Bank left"},
    {cmd = 189, name = "Bank right"},
    {cmd = 190, name = "Local camera rotation mode"},
    {cmd = 191, name = "Decelerate model time"},
    {cmd = 192, name = "Jump to other plane"},
    {cmd = 193, name = "Nose down"},
    {cmd = 194, name = "Nose down end"},
    {cmd = 195, name = "Nose up"},
    {cmd = 196, name = "Nose up end"},
    {cmd = 197, name = "Bank left"},
    {cmd = 198, name = "Bank left end"},
    {cmd = 199, name = "Bank right"},
    {cmd = 200, name = "Bank right end"},
    {cmd = 201, name = "Rudder left"},
    {cmd = 202, name = "Rudder left end"},
    {cmd = 203, name = "Rudder right"},
    {cmd = 204, name = "Rudder right end"},
    {cmd = 205, name = "View up right"},
    {cmd = 206, name = "View down right"},
    {cmd = 207, name = "View down left"},
    {cmd = 208, name = "View up left"},
    {cmd = 209, name = "View stop"},
    {cmd = 210, name = "View up right slow"},
    {cmd = 211, name = "View down right slow"},
    {cmd = 212, name = "View down left slow"},
    {cmd = 213, name = "View up left slow"},
    {cmd = 214, name = "View stop slow"},
    {cmd = 215, name = "Stop trimming"},
    {cmd = 226, name = "Scan zone up right"},
    {cmd = 227, name = "Scan zone down right"},
    {cmd = 228, name = "Scan zone down left"},
    {cmd = 229, name = "Scan zone up left"},
    {cmd = 230, name = "Scan zone stop"},
    {cmd = 231, name = "Radar antenna up right"},
    {cmd = 232, name = "Radar antenna down right"},
    {cmd = 233, name = "Radar antenna down left"},
    {cmd = 234, name = "Radar antenna up left"},
    {cmd = 235, name = "Radar antenna stop"},
    {cmd = 236, name = "Save snap view angles"},
    {cmd = 237, name = "Cockpit panel view toggle"},
    {cmd = 245, name = "Coordinates units toggle"},
    {cmd = 246, name = "Disable time acceleration"},
    {cmd = 252, name = "Automatic spin recovery"},
    {cmd = 253, name = "Speed retention"},
    {cmd = 254, name = "Easy landing"},
    {cmd = 258, name = "Threat missile padlock"},
    {cmd = 259, name = "All missiles padlock"},
    {cmd = 261, name = "Marker state"},
    {cmd = 262, name = "Decrease radar scan area"},
    {cmd = 263, name = "Increase radar scan area"},
    {cmd = 264, name = "Marker state plane"},
    {cmd = 265, name = "Marker state rocket"},
    {cmd = 266, name = "Marker state plane ship"},
    {cmd = 267, name = "Ask AWACS home airbase"},
    {cmd = 268, name = "Ask AWACS available tanker"},
    {cmd = 269, name = "Ask AWACS nearest target"},
    {cmd = 270, name = "Ask AWACS declare target"},
    {cmd = 271, name = "Easy radar"},
    {cmd = 272, name = "Auto lock nearest aircraft"},
    {cmd = 273, name = "Auto lock center aircraft"},
    {cmd = 274, name = "Auto lock next aircraft"},
    {cmd = 275, name = "Auto lock previous aircraft"},
    {cmd = 276, name = "Auto lock nearest surface target"},
    {cmd = 277, name = "Auto lock center surface target"},
    {cmd = 278, name = "Auto lock next surface target"},
    {cmd = 279, name = "Auto lock previous surface target"},
    {cmd = 280, name = "Change cannon rate of fire"},
    {cmd = 281, name = "Change ripple quantity"},
    {cmd = 282, name = "Change ripple interval"},
    {cmd = 283, name = "Switch master arm"},
    {cmd = 284, name = "Change release mode"},
    {cmd = 285, name = "Change radar RWS/TWS"},
    {cmd = 286, name = "Change RWR/SPO mode"},
    {cmd = 288, name = "Flight clock reset"},
    {cmd = 289, name = "Zoom in slow stop"},
    {cmd = 290, name = "Zoom out slow stop"},
    {cmd = 291, name = "Zoom in stop"},
    {cmd = 292, name = "Zoom out stop"},
    {cmd = 295, name = "View horizontal stop"},
    {cmd = 296, name = "View vertical stop"},
    {cmd = 298, name = "Jump to fly-by view"},
    {cmd = 299, name = "Camera jiggle"},
    {cmd = 300, name = "Cockpit illumination"},
    {cmd = 308, name = "Change ripple interval down"},
    {cmd = 309, name = "Engines start"},
    {cmd = 310, name = "Engines stop"},
    {cmd = 311, name = "Left engine start"},
    {cmd = 312, name = "Right engine start"},
    {cmd = 313, name = "Left engine stop"},
    {cmd = 314, name = "Right engine stop"},
    {cmd = 315, name = "Power on/off"},
    {cmd = 316, name = "Altimeter pressure increase"},
    {cmd = 317, name = "Altimeter pressure decrease"},
    {cmd = 318, name = "Altimeter pressure stop"},
    {cmd = 321, name = "Fast mouse in views"},
    {cmd = 322, name = "Slow mouse in views"},
    {cmd = 323, name = "Normal mouse in views"},
    {cmd = 326, name = "HUD only view"},
    {cmd = 327, name = "Recover my plane"},
    {cmd = 328, name = "Toggle gear light Near/Far/Off"},
    {cmd = 331, name = "Fast keyboard in views"},
    {cmd = 332, name = "Slow keyboard in views"},
    {cmd = 333, name = "Normal keyboard in views"},
    {cmd = 334, name = "Zoom in external views"},
    {cmd = 335, name = "Stop zoom in external views"},
    {cmd = 336, name = "Zoom out external views"},
    {cmd = 337, name = "Stop zoom out external views"},
    {cmd = 338, name = "Default zoom external views"},
    {cmd = 341, name = "A2G combat view"},
    {cmd = 342, name = "Camera view up-left"},
    {cmd = 343, name = "Camera view up-right"},
    {cmd = 344, name = "Camera view down-left"},
    {cmd = 345, name = "Camera view down right"},
    {cmd = 346, name = "Camera pan mode toggle"},
    {cmd = 347, name = "Return the camera"},
    {cmd = 348, name = "Trains/cars toggle"},
    {cmd = 349, name = "Launch permission override"},
    {cmd = 350, name = "Release weapon"},
    {cmd = 351, name = "Stop release weapon"},
    {cmd = 352, name = "Return camera base"},
    {cmd = 353, name = "Camera view up-left slow"},
    {cmd = 354, name = "Camera view up-right slow"},
    {cmd = 355, name = "Camera view down-left slow"},
    {cmd = 356, name = "Camera view down-right slow"},
    {cmd = 357, name = "Drop flare once"},
    {cmd = 358, name = "Drop chaff once"},
    {cmd = 359, name = "Rear view"},
    {cmd = 360, name = "Scores window"},
    {cmd = 386, name = "PlaneStabPitchBank"},
    {cmd = 387, name = "PlaneStabHbarBank"},
    {cmd = 388, name = "PlaneStabHorizont"},
    {cmd = 389, name = "PlaneStabHbar"},
    {cmd = 390, name = "PlaneStabHrad"},
    {cmd = 391, name = "Active IR jamming on/off"},
    {cmd = 392, name = "Laser range-finder on/off"},
    {cmd = 393, name = "Night TV on/off"},
    {cmd = 394, name = "Change radar PRF"},
    {cmd = 395, name = "Keep F11 camera altitude"},
    {cmd = 396, name = "SnapView0"},
    {cmd = 397, name = "SnapView1"},
    {cmd = 398, name = "SnapView2"},
    {cmd = 399, name = "SnapView3"},
    {cmd = 400, name = "SnapView4"},
    {cmd = 401, name = "SnapView5"},
    {cmd = 402, name = "SnapView6"},
    {cmd = 403, name = "SnapView7"},
    {cmd = 404, name = "SnapView8"},
    {cmd = 405, name = "SnapView9"},
    {cmd = 406, name = "SnapViewStop"},
    {cmd = 407, name = "F11 view binocular mode"},
    {cmd = 408, name = "PlaneStabCancel"},
    {cmd = 409, name = "ThreatWarnSoundVolumeDown"},
    {cmd = 410, name = "ThreatWarnSoundVolumeUp"},
    {cmd = 411, name = "F11 binocular laser range-finder"},
    {cmd = 412, name = "PlaneIncreaseBase_Distance"},
    {cmd = 413, name = "PlaneDecreaseBase_Distance"},
    {cmd = 414, name = "PlaneStopBase_Distance"},
    {cmd = 425, name = "F11 binocular IR mode on/off"},
    {cmd = 426, name = "F8 view player/all targets"},
    {cmd = 427, name = "Plane autopilot override on"},
    {cmd = 428, name = "Plane autopilot override off"},
    {cmd = 429, name = "Plane route autopilot on/off"},
    {cmd = 430, name = "Gear up"},
    {cmd = 431, name = "Gear down"},
}